<?php

return [
    "name" => "product",
    "title" => "Producten",
    "description" => "Producten module",
    "module_name" => [
        "single" => "Product",
        "multiple" => "Producten"
    ],
    "tabtitle" => "title",
    "type" => "module",
    "active" => true,
    "locale" => "nl",
    "data" => [],
    "sort" => 999,
    "route" => null,
    "url" => null,
    "icon" => null,
    "rights" => null,
    "ereg" => [],
    "settings" => [],
    "fields" => [
        "active" => [
            "active" => true,
            "type" => "checkbox",
            "title" => "Actief",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "capacity" => [
            "active" => true,
            "type" => "number",
            "title" => "Capaciteit",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "block_size" => [
            "active" => true,
            "type" => "number",
            "title" => "Blok grootte",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "product_type" => [
            "active" => true,
            "type" => "select",
            "title" => "Product type",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "time_unit" => [
            "active" => true,
            "type" => "select",
            "title" => "Tijd eenheid",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "resource_id" => [
            "active" => true,
            "type" => "select",
            "title" => "Resource",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "slug" => [
            "active" => true,
            "type" => "text",
            "title" => "Slug",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "unit_type" => [
            "active" => true,
            "type" => "select",
            "title" => "Eenheid type",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "unit_step" => [
            "active" => true,
            "type" => "number",
            "title" => "Eenheid stap",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "min_order_qty" => [
            "active" => true,
            "type" => "number",
            "title" => "Min. bestelhoeveelheid",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "max_order_qty" => [
            "active" => true,
            "type" => "number",
            "title" => "Max. bestelhoeveelheid",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "price_per_unit" => [
            "active" => true,
            "type" => "number",
            "title" => "Prijs per eenheid",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "tax_rate" => [
            "active" => true,
            "type" => "number",
            "title" => "BTW percentage",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "calc_mode" => [
            "active" => true,
            "type" => "select",
            "title" => "Berekeningswijze",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "wastage_pct" => [
            "active" => true,
            "type" => "number",
            "title" => "Verspilling %",
            "read" => true,
            "required" => false,
            "edit" => true,
            "step" => 0.01,
        ],
        "rounding_mode" => [
            "active" => true,
            "type" => "select",
            "title" => "Afrondingswijze",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "length_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Lengte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "width_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Breedte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "height_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Hoogte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "dimension_unit" => [
            "active" => true,
            "type" => "select",
            "title" => "Afmeting eenheid",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
    ]
];
