<?php

return [
    "name" => "variant",
    "title" => "Varianten",
    "description" => "Varianten module",
    "module_name" => [
        "single" => "Variant",
        "multiple" => "Varianten"
    ],
    "tabtitle" => "title",
    "type" => "module",
    "active" => true,
    "locale" => "nl",
    "data" => [],
    "sort" => 999,
    "route" => null,
    "url" => null,
    "icon" => null,
    "rights" => null,
    "ereg" => [],
    "settings" => [],
    "fields" => [
        "locale" => [
            "active" => true,
            "type" => "text",
            "title" => "Taal",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "uploads" => [
            "active" => false,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
        ],
        "sku" => [
            "active" => true,
            "type" => "text",
            "title" => "SKU",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "title" => [
            "active" => true,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "active" => [
            "active" => true,
            "type" => "boolean",
            "title" => "Actief",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "variant_key" => [
            "active" => true,
            "type" => "text",
            "title" => "Variant sleutel",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "price_override_excl" => [
            "active" => true,
            "type" => "number",
            "title" => "Prijs override (excl. BTW)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "tax_rate" => [
            "active" => true,
            "type" => "number",
            "title" => "BTW percentage",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "stock_qty" => [
            "active" => true,
            "type" => "number",
            "title" => "Voorraad",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "capacity" => [
            "active" => true,
            "type" => "number",
            "title" => "Capaciteit",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "unit_type" => [
            "active" => true,
            "type" => "select",
            "title" => "Eenheid type",
            "read" => true,
            "required" => false,
            "edit" => true,
            "options" => [
                "piece" => "Stuk",
                "meter" => "Meter",
                "m2" => "Vierkante meter",
                "m3" => "Kubieke meter"
            ]
        ],
        "unit_step" => [
            "active" => true,
            "type" => "number",
            "title" => "Eenheid stap",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "calc_mode" => [
            "active" => true,
            "type" => "select",
            "title" => "Berekeningswijze",
            "read" => true,
            "required" => false,
            "edit" => true,
            "options" => [
                "direct_length" => "Directe lengte",
                "dimensions_2d" => "2D afmetingen",
                "dimensions_3d" => "3D afmetingen"
            ]
        ],
        "wastage_pct" => [
            "active" => true,
            "type" => "number",
            "title" => "Verspilling percentage",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "rounding_mode" => [
            "active" => true,
            "type" => "select",
            "title" => "Afrondingswijze",
            "read" => true,
            "required" => false,
            "edit" => true,
            "options" => [
                "round" => "Afronden",
                "ceil" => "Naar boven",
                "floor" => "Naar beneden"
            ]
        ],
        "length_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Lengte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "width_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Breedte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "height_mm" => [
            "active" => true,
            "type" => "number",
            "title" => "Hoogte (mm)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
    ]
];
