<?php

return [
    "name" => "category",
    "title" => "Categorieën",
    "description" => "Product categorieën module",
    "module_name" => [
        "single" => "Categorie",
        "multiple" => "Categorieën"
    ],
    "tabtitle" => "name",
    "type" => "module",
    "active" => true,
    "locale" => "nl",
    "data" => [],
    "sort" => 998,
    "route" => null,
    "url" => null,
    "icon" => null,
    "rights" => null,
    "ereg" => [],
    "settings" => [],
    "fields" => [
        "locale" => [
            "active" => true,
            "type" => "text",
            "title" => "Taal",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "uploads" => [
            "active" => true,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
        ],
        "name" => [
            "active" => true,
            "type" => "text",
            "title" => "Naam",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "slug" => [
            "active" => true,
            "type" => "text",
            "title" => "Slug",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "description" => [
            "active" => true,
            "type" => "textarea",
            "title" => "Beschrijving",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "parent_id" => [
            "active" => true,
            "type" => "select",
            "title" => "Hoofdcategorie",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "sort" => [
            "active" => true,
            "type" => "number",
            "title" => "Sortering",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "active" => [
            "active" => true,
            "type" => "checkbox",
            "title" => "Actief",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "image" => [
            "active" => true,
            "type" => "text",
            "title" => "Afbeelding",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
    ]
];
